# Generated by Django 3.1.2 on 2020-10-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201028_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mainimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
